# Default values for autom8s.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  # uncomment and fill registry name
  # registry: 
  name: autom8s
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 4000

namespace: default

# for the ingress functionallity - the ingress is the controller which exposes the newly deployed service
# Refer to the docs for more details
ingress:
  ingressNamespace: default
  minPort: 20000
  maxPort: 30000
  ingressLabel: ingress

# configuration for the rbac namespaces, service accounts, roles and binding names
rbac:
  helmServiceAccount: helm
  helmRole: tiller-user
  tillerServiceAccount: tiller
  tillerRoleBindingName: tiller-user-binding
  tillerNamespace: kube-system
