apiVersion: v1
appVersion: "1.0"
description: Dynamically deploy applications to kubernetes cluster and expose them externally via a single IP
name: on-demand-micro-services-deployment-k8s
version: 0.1.0
